### ISSUE TITLE
Lots of Python runtime error

### ISSUE THREAD

**Issue by fakhrizulkifli** [cloudburst/libheap#16]
I don't know how to properly use the functions available from libheap. So i tried to get a chunk size using one of the features `chunksize(p)` and i got this:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/libheap.py", line 75, in chunksize
    return (p.size & ~SIZE_BITS)
AttributeError: 'int' object has no attribute 'size'
Error while executing Python code.
```

In facts, there is a lot of others functions which triggers the same exception such as no attributes `fd`, `size`. Plus when i tried other example from the README.md, `p *(mchunkptr) 0x804b000:

```
Python Exception <class 'TypeError'> non-empty format string passed to object.__format__: 
$1 = 
```

`print_mstats`:
```
==================================Malloc Stats==================================
Python Exception <class 'TypeError'> %x format: an integer is required, not gdb.Value: 
Error occurred in Python command: %x format: an integer is required, not gdb.Value
```

**Comment by cloudburst** [comment]
All of the convenience functions need a python object not a literal int object.  So for example:

p = malloc_chunk(0x608790)
chunksize(p)

And print_mstats is fixed with 07db4b1591016b2718a7c5fdd8f452a5dcb1d52a so make sure you have the latest checkout.

If you play around with these and still have errors where the functions are being called with the proper arguments then please reopen with an individual test case.

**Comment by cloudburst** [comment]
Hi @fakhrizulkifli 

I rewrote a lot of the error handling and documentation in the latest git checkout so you may find it easier to use now.  Sorry about that.  Please let me know if you find any more issues.

**Comment by fakhrizulkifli** [comment]
Thank you very much @cloudburst. I very much appreciated the effort. Things are better with the documentation.
