### ISSUE TITLE
Colorful print issue with peda

### ISSUE THREAD

**Issue by BrieflyX** [cloudburst/libheap#19]
After the modification of printing utils, I found this version couldn't work well with peda. I used to utilize `source libheap.py` in my `.gdbinit`. But it tampered peda's running and messed up the color print.

**Comment by cloudburst** [comment]
I'll look into this soon, although personally I have moved to pwndbg and voltron as more modern replacements for the peda frontend.

**Comment by cloudburst** [comment]
Well I don't know enough about the peda internals to fix this currently but it looks like a conflict with peda's buffering code.  The following diff fixes it for me so both peda and libheap colors work:

https://gist.github.com/cloudburst/f5b6ec91b1e2fdad9ebb4b77bb13fece

Since I think this is an issue on the peda side I'm closing this issue.

**Comment by cloudburst** [comment]
hi @BrieflyX 

I just finished rewriting a lot of the library.  There is glibc support up until 2.25 now.  There is still no ARM/raspberry pi support but that is a future TODO (I've only had time to test Intel 32/64bit).  Thank you very much for all of your pull requests and Issues!  Please let me know if you find any more bugs.  I hope this solved your peda issue as well.
